version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    environment:
      - DASH_USER=${DASH_USER}
      - DASH_PW=${DASH_PW}

  nginx:
    build:
      context: .
      dockerfile: nginx-server/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - flask-app
